image:
  repository: nginxdemos/hello
  tag: plain-text
replicaCount: 1
service:
  type: ClusterIP
  port: 80
resources:
  requests:
   cpu: 50m
   memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
